---
- name: Install OpenLDAP packages
  dnf:
    name:
      - openldap
      - openldap-servers
      - openldap-clients
      - openldap-devel
    state: present

- name: Create LDAP system group
  ansible.builtin.group:
    name: ldap
    state: present
    system: yes
    gid: 55

- name: Create LDAP system user
  ansible.builtin.user:
    name: ldap
    state: present
    system: yes
    uid: 55
    group: ldap
    home: /var/lib/ldap
    create_home: no
    shell: /sbin/nologin

- name: Create OpenLDAP data directory
  file:
    path: /var/lib/ldap
    state: directory
    owner: ldap
    group: ldap
    mode: '0750'

- name: Create OpenLDAP config directory
  file:
    path: /etc/openldap/slapd.d
    state: directory
    owner: ldap
    group: ldap
    mode: '0750'

- name: Copy slapd.conf template
  template:
    src: slapd.conf.j2
    dest: /etc/openldap/slapd.conf
    owner: root
    group: root
    mode: '0640'
  notify: restart slapd

- name: Copy LDIF template for initial setup
  template:
    src: initial.ldif.j2
    dest: /etc/openldap/initial.ldif
    owner: ldap
    group: ldap
    mode: '0640'

- name: Check if slapd service file exists
  ansible.builtin.stat:
    path: /usr/lib/systemd/system/slapd.service  # Verify this path matches your OS
    get_checksum: no
  register: slapd_service_file

- name: Create slapd systemd service file
  ansible.builtin.template:
    src: slapd.service.j2
    dest: /usr/lib/systemd/system/slapd.service
    mode: '0644'
  when: not slapd_service_file.stat.exists
  notify:
    - daemon-reload
    - restart slapd

- name: Start and enable slapd service
  ansible.builtin.systemd:
    name: slapd
    state: started
    enabled: yes
  notify: restart slapd

- name: Wait for slapd to be ready
  wait_for:
    port: 389
    timeout: 30

- name: Stop slapd service before database initialization
  service:
    name: slapd
    state: stopped

- name: Remove existing database files
  file:
    path: /var/lib/ldap
    state: absent

- name: Create new database directory
  file:
    path: /var/lib/ldap
    state: directory
    owner: ldap
    group: ldap
    mode: '0750'

- name: Create DB_CONFIG file
  copy:
    content: |
      set_cachesize 0 2097152 0
      set_lk_max_objects 1500
      set_lk_max_locks 1500
      set_lk_max_lockers 1500
      set_flags DB_LOG_AUTOREMOVE
    dest: /var/lib/ldap/DB_CONFIG
    owner: ldap
    group: ldap
    mode: '0640'

- name: Initialize OpenLDAP database
  command: slapadd -F /etc/openldap/slapd.d -n 0 -l /etc/openldap/initial.ldif
  become: yes
  become_user: ldap
  environment:
    HOME: /var/lib/ldap

- name: Set permissions on slapd directories
  file:
    path: "{{ item }}"
    owner: ldap
    group: ldap
    mode: '0750'
    recurse: yes
  loop:
    - /var/lib/ldap
    - /etc/openldap/slapd.d

- name: Start slapd service
  service:
    name: slapd
    state: started

- name: Create admin password hash
  command: slappasswd -s "{{ ldap_admin_password }}"
  register: admin_password_hash
  no_log: true

- name: Configure admin password
  ldap_entry:
    dn: "{{ ldap_root_dn }}"
    objectClass: organizationalRole
    objectClass: simpleSecurityObject
    cn: admin
    userPassword: "{{ admin_password_hash.stdout }}"
  become: yes

- name: Copy users and groups LDIF template
  template:
    src: users_groups.ldif.j2
    dest: /etc/openldap/users_groups.ldif
    owner: ldap
    group: ldap
    mode: '0640'

- name: Import users and groups
  command: ldapadd -x -D "{{ ldap_root_dn }}" -w "{{ ldap_admin_password }}" -f /etc/openldap/users_groups.ldif
  become: yes
  no_log: true