---
- name: restart munge
  service:
    name: munge
    state: restarted

- name: restart slurmd
  service:
    name: slurmd
    state: restarted

- name: reload firewall
  service:
    name: firewalld
    state: reloaded