---
- name: Reiniciar EAR daemon
  service:
    name: eard
    state: restarted
  ignore_errors: yes

- name: Reiniciar SLURM
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - slurmctld
    - slurmd
  ignore_errors: yes

- name: Recargar systemd
  shell: systemctl daemon-reload