---
# Default variables for HPL benchmark

# Package dependencies
hpl_dependencies:
  - gcc
  - gcc-c++
  - gcc-gfortran
  - make
  - wget
  - tar
  - bzip2
  - environment-modules
  - numactl

# MPI implementation (openmpi or mpich)
mpi_implementation: "openmpi"
mpi_packages:
  - "{{ mpi_implementation }}"
  - "{{ mpi_implementation }}-devel"

# BLAS/LAPACK implementation
blas_implementation: "openblas"
blas_packages:
  - "{{ blas_implementation }}"
  - "{{ blas_implementation }}-openmp"  # Use openmp version instead of -devel

# HPL source and build settings
hpl_version: "2.3"
hpl_source_url: "http://www.netlib.org/benchmark/hpl/hpl-{{ hpl_version }}.tar.gz"
hpl_download_dir: "/tmp"
hpl_build_dir: "/opt/hpl-{{ hpl_version }}"
hpl_install_dir: "/opt/hpl"
hpl_run_dir: "/opt/hpl/runs"

# SSH settings
ssh_key_type: "rsa"
ssh_key_bits: 4096
ssh_key_file: "/root/.ssh/id_{{ ssh_key_type }}"

# HPL run settings
hpl_run_benchmark: true
hpl_mpi_processes: "{{ ansible_processor_vcpus }}"
hpl_threads_per_process: 1
hpl_problem_size: 20000  # N - matrix size
hpl_block_size: 192      # NB - block size
hpl_grid_p: 2            # P - process grid rows
hpl_grid_q: 2            # Q - process grid columns