---
- name: Desplegar Energy Aware Runtime (EAR) en nodo manager
  hosts: ear_manager
  become: yes
  
  roles:
    - ear

- name: Desplegar Energy Aware Runtime Daemon (eard) en nodos de cómputo
  hosts: ear_nodes
  become: yes
  
  roles:
    - ear