---
- name: Deploy Proxmox Power Monitoring
  hosts: proxmox
  become: yes
  
  vars_files:
    - inventory/group_vars/all.yml
    - inventory/group_vars/monitoring_servers/vault.yml
  roles:
    - proxmox_monitoring
