---
- name: Deploy SLURM Control Server
  hosts: slurmctld
  become: true
  tasks:
    - name: Fix MungeSocketPath in slurm.conf
      lineinfile:
        path: /etc/slurm/slurm.conf
        regexp: ".*MungeSocketPath=.*"
        state: absent
      notify: restart slurmctld

    - name: Create SLURM user groups
      group:
        name: "{{ item.name }}"
        state: present
      loop: "{{ slurm_groups }}"

    - name: Create SLURM accounts for each group
      shell: |
        sacctmgr -i add account {{ item.name }} Description="{{ item.description }}"
      loop: "{{ slurm_groups }}"
      register: sacctmgr_account_result
      failed_when: sacctmgr_account_result.rc != 0 and '"Nothing new added" not in sacctmgr_account_result.stderr'
      changed_when: '"Nothing new added" not in sacctmgr_account_result.stderr'

    - name: Add users to SLURM accounts
      shell: |
        sacctmgr -i add user {{ item.1 }} Account={{ item.0.name }}
      loop: "{{ slurm_groups|subelements('members') }}"
      when: item.1 != ""
      register: sacctmgr_user_result
      failed_when: sacctmgr_user_result.rc != 0 and '"Nothing new added" not in sacctmgr_user_result.stderr'
      changed_when: '"Nothing new added" not in sacctmgr_user_result.stderr'

    - name: Verify SLURM associations
      shell: sacctmgr show assoc format=account,user
      register: slurm_assoc
      changed_when: false

    - name: Display SLURM associations
      debug:
        msg: "{{ slurm_assoc.stdout_lines }}"

  handlers:
    - name: restart slurmctld
      service:
        name: slurmctld
        state: restarted

  roles:
    - epel
    - slurmctld
