---
# AutoFS client configuration role
# This role installs and configures AutoFS for NFS mounts

- name: Install AutoFS packages
  package:
    name:
      - autofs
      - nfs-utils
    state: present

- name: Configure AutoFS master configuration
  template:
    src: auto.master.j2
    dest: /etc/auto.master
    owner: root
    group: root
    mode: '0644'
  notify: restart autofs

- name: Configure AutoFS home maps
  template:
    src: auto.home.j2
    dest: /etc/auto.home
    owner: root
    group: root
    mode: '0644'
  notify: restart autofs

- name: Configure AutoFS applications maps
  template:
    src: auto.apps.j2
    dest: /etc/auto.apps
    owner: root
    group: root
    mode: '0644'
  notify: restart autofs

- name: Enable and start AutoFS service
  systemd:
    name: autofs
    enabled: yes
    state: started

- name: Configure firewall for NFS client
  firewalld:
    service: nfs
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_facts.services['firewalld.service'] is defined and ansible_facts.services['firewalld.service'].state == 'running'