---
- name: Crear archivo de configuración eard.conf
  template:
    src: eard.conf.j2
    dest: "{{ ear_etc }}/eard.conf"
    mode: '0644'
  notify: Reiniciar EAR daemon

- name: Crear archivo de servicio systemd para eard
  template:
    src: eard.service.j2
    dest: "/etc/systemd/system/eard.service"
    mode: '0644'
  notify: Recargar systemd

- name: Habilitar e iniciar servicio eard
  service:
    name: eard
    state: started
    enabled: yes
    daemon_reload: yes