---
- name: Crear directorio para plugins de SLURM
  file:
    path: "/etc/slurm/plugstack.conf.d"
    state: directory
    mode: '0755'

- name: Verificar si existe el plugin ear.so
  stat:
    path: "{{ ear_install_path }}/lib/plugins/ear.so"
  register: ear_plugin_exists

- name: Verificar si existe el plugin libear_slurm.so
  stat:
    path: "{{ ear_install_path }}/lib/plugins/libear_slurm.so"
  register: libear_slurm_exists

- name: Determinar el nombre del plugin a usar
  set_fact:
    ear_plugin_name: "{{ 'ear.so' if ear_plugin_exists.stat.exists else 'libear_slurm.so' }}"

- name: Crear enlace simbólico para el plugin de SLURM
  file:
    src: "{{ ear_install_path }}/lib/plugins/ear.so"
    dest: "{{ ear_install_path }}/lib/plugins/libear_slurm.so"
    state: link
  when: ear_plugin_exists.stat.exists and not libear_slurm_exists.stat.exists

- name: Crear archivo de configuración para el plugin de SLURM
  template:
    src: ear_slurm.conf.j2
    dest: "/etc/slurm/plugstack.conf.d/ear.conf"
    mode: '0644'
  notify: Reiniciar SLURM

- name: Asegurar que plugstack.conf incluye el directorio de plugins
  lineinfile:
    path: "/etc/slurm/plugstack.conf"
    line: "include /etc/slurm/plugstack.conf.d/*.conf"
    state: present
    create: yes
    mode: '0644'
  notify: Reiniciar SLURM