---
- name: Update package database
  dnf:
    update_cache: yes

- name: Add Docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install required packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - python3-pip
    state: present

- name: Install Python Docker module with pip
  pip:
    name: docker
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create directories for monitoring
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - /opt/monitoring/prometheus
    - /opt/monitoring/prometheus/data
    - /opt/monitoring/grafana
    - /opt/monitoring/grafana/data
    - /opt/monitoring/grafana/provisioning/datasources
    - /opt/monitoring/grafana/provisioning/dashboards
    - /opt/monitoring/grafana/dashboards

- name: Copy Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: /opt/monitoring/prometheus/prometheus.yml
    mode: "0644"

- name: Copy Prometheus alert rules
  template:
    src: alert_rules.yml.j2
    dest: /opt/monitoring/prometheus/alert_rules.yml
    mode: "0644"

- name: Copy Grafana datasource configuration
  template:
    src: datasource.yml.j2
    dest: /opt/monitoring/grafana/provisioning/datasources/datasource.yml
    mode: "0644"

- name: Copy Grafana dashboard provisioning configuration
  template:
    src: dashboards.yml.j2
    dest: /opt/monitoring/grafana/provisioning/dashboards/dashboards.yml
    mode: "0644"

- name: Copy Node Exporter dashboard
  copy:
    src: node_exporter.json
    dest: /opt/monitoring/grafana/dashboards/node_exporter.json
    mode: "0644"

- name: Copy SLURM Exporter dashboard
  copy:
    src: slurm_exporter.json
    dest: /opt/monitoring/grafana/dashboards/slurm_exporter.json
    mode: "0644"
  when: "'slurmctld' in groups"

- name: Set proper permissions for monitoring directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "1000"
    group: "1000"
    recurse: yes
  with_items:
    - /opt/monitoring/prometheus/data
    - /opt/monitoring/grafana/data

- name: Copy docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/monitoring/docker-compose.yml
    mode: "0644"

- name: Start monitoring stack with docker-compose
  command: docker compose -f /opt/monitoring/docker-compose.yml up -d
  args:
    chdir: /opt/monitoring