---
- name: Install SLURM client packages
  package:
    name:
      - slurm
      - slurm-contribs
      - slurm-pam_slurm
    state: present

- name: Install development tools and compilers
  package:
    name:
      - gcc
      - gcc-c++
      - make
      - cmake
      - autoconf
      - automake
      - libtool
      - environment-modules
      - git
    state: present

- name: Ensure SLURM config directory exists
  file:
    path: /etc/slurm
    state: directory
    mode: "0755"

- name: Create slurm group
  group:
    name: slurm
    gid: 982
    state: present

- name: Create slurm user
  user:
    name: slurm
    uid: 982
    group: slurm
    state: present

- name: Add slurm01 to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[groups['slurmctld'][0]]['ansible_host'] }} slurm01"
    state: present

- name: Fetch SLURM configuration from controller node
  shell: scp root@{{ hostvars[groups['slurmctld'][0]]['ansible_host'] }}:/etc/slurm/slurm.conf /etc/slurm/slurm.conf
  args:
    creates: /etc/slurm/slurm.conf
  become: yes

- name: Set proper permissions on slurm.conf
  file:
    path: /etc/slurm/slurm.conf
    owner: slurm
    group: slurm
    mode: "0644"

- name: Ensure munge directory exists
  file:
    path: /etc/munge
    state: directory
    owner: munge
    group: munge
    mode: "0700"

- name: Fetch munge key from controller node
  shell: scp root@{{ hostvars[groups['slurmctld'][0]]['ansible_host'] }}:/etc/munge/munge.key /etc/munge/munge.key
  args:
    creates: /etc/munge/munge.key
  become: yes

- name: Set proper permissions on munge key
  file:
    path: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: "0400"
  notify: restart munge

- name: Start and enable munge service
  service:
    name: munge
    state: started
    enabled: yes

- name: Configure user resource limits
  template:
    src: 99-hpc-limits.conf.j2
    dest: /etc/security/limits.d/99-hpc-limits.conf
    mode: "0644"

- name: Configure SSH for X11 forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding'
    line: 'X11Forwarding yes'
    state: present
  notify: restart sshd

- name: Install monitoring client
  include_role:
    name: node_exporter