---
- name: Setup NFS Shares for HPC
  hosts: nfs_servers
  become: yes
  
  vars_files:
    - inventory/group_vars/all/main.yml
    
  tasks:
    - name: Create HPC application directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - /apps
        - /apps/software
        - /apps/libraries
        - /apps/data
        - /scratch
        
    - name: Create sample files in software directory
      copy:
        dest: "/apps/software/{{ item }}"
        content: "This is a sample {{ item }} file for HPC applications"
        mode: '0644'
      loop:
        - README.txt
        - sample_app.sh
        - environment.conf
        
    - name: Create sample library files
      copy:
        dest: "/apps/libraries/{{ item }}"
        content: "Sample library file: {{ item }}"
        mode: '0644'
      loop:
        - libsample.so
        - libmath.so
        - libhpc.so
        
    - name: Create sample data files
      copy:
        dest: "/apps/data/{{ item }}"
        content: "Sample data file: {{ item }}"
        mode: '0644'
      loop:
        - dataset1.dat
        - reference.dat
        - parameters.conf
        
    - name: Create scratch directory structure
      file:
        path: "/scratch/{{ item }}"
        state: directory
        mode: '0777'
        owner: root
        group: root
      loop:
        - jobs
        - temp
        - shared
        
    - name: Configure NFS exports
      template:
        src: templates/exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'
      notify: reload nfs exports
      
    - name: Ensure NFS services are running
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - rpcbind
        - nfs-server
        
  handlers:
    - name: reload nfs exports
      command: exportfs -ra