---
# Main playbook for HPC Cluster Deployment
# This is the entry point for the entire deployment

- name: Include core infrastructure playbooks
  import_playbook: playbooks/core/dns.yml
  tags: dns

- name: Include firewall configuration
  import_playbook: playbooks/core/firewall.yml
  tags: firewall

- name: Include NFS server setup
  import_playbook: playbooks/core/nfs-server.yml
  tags: nfs

- name: Include authentication playbooks
  import_playbook: playbooks/auth/openldap.yml
  tags: ldap

- name: Include LDAP client configuration
  import_playbook: playbooks/auth/ldap-client.yml
  tags: ldap-client

- name: Include SLURM database setup
  import_playbook: playbooks/slurm/slurmdbd.yml
  tags: slurm-db

- name: Include SLURM controller setup
  import_playbook: playbooks/slurm/slurmctld.yml
  tags: slurm-controller

- name: Include compute node setup
  import_playbook: playbooks/slurm/compute.yml
  tags: compute

- name: Include login node setup
  import_playbook: playbooks/slurm/login.yml
  tags: login

- name: Include monitoring setup
  import_playbook: playbooks/monitoring/monitoring.yml
  tags: monitoring

- name: Include reporting setup
  import_playbook: playbooks/reporting/reporting.yml
  tags: reporting
