---
- name: restart prometheus container
  command: docker compose -f /opt/monitoring/docker-compose.yml restart prometheus
  args:
    chdir: /opt/monitoring

- name: restart grafana container
  command: docker compose -f /opt/monitoring/docker-compose.yml restart grafana
  args:
    chdir: /opt/monitoring

- name: reload systemd
  command: systemctl daemon-reload

- name: restart slurm-exporter
  service:
    name: slurm-exporter
    state: restarted

- name: restart docker-compose
  community.docker.docker_compose:
    project_src: /opt/monitoring
    restarted: yes