name: CI Status Monitor

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow status
        id: check_status
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "STATUS=PASSING" >> $GITHUB_OUTPUT
          else
            echo "STATUS=FAILING" >> $GITHUB_OUTPUT
          fi

      - name: Update README badge
        run: |
          sed -i "s|https://img.shields.io/badge/CI-.*|https://img.shields.io/badge/CI-${{ steps.check_status.outputs.STATUS }}-brightgreen.svg|g" README.md
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update CI status badge" || exit 0
          git push