name: Integration Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'tests/integration_tests/**'
      - 'playbooks/**'
      - 'roles/**'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible pytest pytest-testinfra
      
      - name: Run integration tests
        run: |
          echo "Running integration tests..."
          cd tests
          
          # Run all integration tests
          for test_file in integration_tests/*.yml; do
            if [ -f "$test_file" ]; then
              echo "Running test: $test_file"
              ansible-playbook "$test_file" -i inventory/hosts --connection=local || echo "Test $test_file failed but continuing..."
            fi
          done
        continue-on-error: true
      
      - name: Run component tests
        run: |
          echo "Running component tests..."
          cd tests
          
          # Run all component tests
          for test_file in component_tests/*.yml; do
            if [ -f "$test_file" ]; then
              echo "Running test: $test_file"
              ansible-playbook "$test_file" -i inventory/hosts --connection=local || echo "Test $test_file failed but continuing..."
            fi
          done
        continue-on-error: true