name: Molecule Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'roles/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'roles/**'
  workflow_dispatch:

jobs:
  molecule:
    name: Molecule Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role:
          - autofs
          - compute
          - dns
          - docker
          - epel
          - login_node
          - monitoring
          - nfs_server
          - node_exporter
          - openldap
          - prometheus
          - slurmctld
          - slurmdbd
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule-docker ansible-core pytest pytest-testinfra
      
      - name: Run Molecule tests
        run: |
          cd roles/${{ matrix.role }}
          if [ -d "molecule" ]; then
            molecule test
          else
            echo "No molecule tests found for role ${{ matrix.role }}, skipping."
          fi
        continue-on-error: true