name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit ansible-lint
      
      - name: Run Bandit security scan
        run: |
          echo "Security Scan Results:" > security_scan_results.log
          echo "======================" >> security_scan_results.log
          echo "" >> security_scan_results.log
          
          # Scan Python files
          echo "Running Bandit on Python files:" >> security_scan_results.log
          find . -name "*.py" -not -path "*/\.*" | xargs bandit -r 2>&1 || true >> security_scan_results.log
          echo "" >> security_scan_results.log
          
          # Scan Ansible files for security issues
          echo "Running Ansible-lint security checks:" >> security_scan_results.log
          ansible-lint --tags security -p 2>&1 || true >> security_scan_results.log
          
          echo "Security scan completed. Check security_scan_results.log for details."
      
      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: security_scan_results.log